services:
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: the_username
            POSTGRES_PASSWORD: the_password
            POSTGRES_DB: the_database
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
