services:
    server:
        image: postinger-backend-dev
        build:
            context: .
            dockerfile: dev.Dockerfile
        volumes:
            - ./:/usr/src/app
        ports:
            - 3003:3003
        environment:
            - POSTGRES_URL=postgres://the_username:the_password@db:5432/the_database

    db:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: the_username
            POSTGRES_PASSWORD: the_password
            POSTGRES_DB: the_database
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
